# Prepare a php dev image with
#  * mod_rewrite enabled
#  * xdebug
#  * pdo, mysqli


FROM php:7.2-apache

# enable mod rewrite
RUN a2enmod rewrite

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql


# Redis and xdebug
RUN pecl install redis-5.1.1 \
    && pecl install xdebug-2.8.1 \
    && docker-php-ext-enable redis xdebug
